using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RockBehavior : MonoBehaviour {
    private void OnCollisionEnter(Collision collision) {
        // 石^碰到任何物件r绦星宄幼
        Debug.Log($"Stone collided with: {collision.gameObject.name}");
        if (collision.gameObject.name == "Player") {
            TrainRockManager.Instance.doDamage();
        }
        Destroy(gameObject); // N石^
    }

    private void OnBecameInvisible() {
        // 石^x_z影C可r绦星宄幼
        Debug.Log("Stone is no longer visible and will be destroyed.");
        Destroy(gameObject); // N石^
    }
}
